name: shuffler_charts
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: admin <email@example.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_components: ^0.14.0-alpha+1
  angular_forms: ^2.1.2
  built_value: ^7.0.4
  built_collection: ^4.3.2
  json_annotation: ^3.0.1
  rxdart: ^0.23.1

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.7.3
  build_test: ^0.10.11
  build_web_compilers: ^2.8.0
  built_value_generator: ^7.0.3
  json_serializable: ^3.2.3
  pedantic: ^1.9.0
  test: ^1.11.0
