name: shuffler_charts
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: admin <email@example.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0
  angular_forms: ^2.1.2
  built_value: ^6.6.0
  built_collection: ^4.2.2
  intl: ^0.15.8
  json_annotation: ^2.4.0
  rxdart: ^0.22.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.2
  build_test: ^0.10.8
  build_web_compilers: ^2.1.0
  built_value_generator: ^6.6.0
  json_serializable: ^3.0.0
  pedantic: ^1.7.0
  test: ^1.5.3
